### ISSUE TITLE
fix the problem "country object has no attribute only_county_mode"

### ISSUE THREAD

**Issue by riajonsoh** [Vitalii16Darn/trpsLabor4#1]
https://github.com/Vitalii16Darn/trpsLabor4/blob/main/euro_diffusion.py
https://github.com/Vitalii16Darn/trpsLabor4/blob/src/country.py
![зображення](https://user-images.githubusercontent.com/107116393/206661097-3c9954b4-e616-495f-bca7-84319facaeef.png)

**Comment by Vitalii16Darn** [comment]
Ok, I've got it!

**Comment by Vitalii16Darn** [comment]
Fixed!

**Comment by riajonsoh** [comment]
Thanks for fixing!
